---
- name: Backup remoto desde servidor Linux (cloud)
  hosts: localhost
  gather_facts: yes
  vars:
    target_host: srv_cloud
    backup_src_paths:
      - "/root"
      - "/home/chichadepardos"
      - "/var/lib/docker"
      - "/etc/docker"
      - "/etc/containers"
    exclude_patterns:
      - "*.log"
      - "*.tmp"
      - "lost+found"
      - "tmp"
      - "*.sock"
      - "/var/lib/docker/containers/*/shm"
    backup_dest_base: "/mnt/backups/{{ target_host }}/{{ ansible_date_time.date }}"
    compressed_file_path: "/mnt/backups/{{ target_host }}_{{ ansible_date_time.date }}.tar.gz"
    rsync_log_path: "/var/log/ansible-backup"

  tasks:
    - name: Obtener remote_user y remote_host desde hostvars
      set_fact:
        remote_user_var: "{{ hostvars[target_host]['remote_user'] }}"
        remote_host: "{{ hostvars[target_host]['remote_host'] }}"

    - name: Crear carpeta base para backups
      ansible.builtin.file:
        path: "{{ backup_dest_base }}"
        state: directory
        mode: '0755'

    - name: Asegurar existencia de carpeta de logs
      ansible.builtin.file:
        path: "{{ rsync_log_path }}"
        state: directory
        mode: '0755'

    - name: Ejecutar backup rsync por cada ruta (sin verbose, sin xattrs)
      ansible.builtin.shell: >
        rsync -aAX --no-xattrs --delete
        {% for pattern in exclude_patterns %}
        --exclude='{{ pattern }}'
        {% endfor %}
        -e "ssh -o StrictHostKeyChecking=no"
        --rsync-path='sudo -n rsync'
        {{ remote_user_var }}@{{ remote_host }}:{{ item }}
        {{ backup_dest_base }}/{{ item | basename }}
        >> {{ rsync_log_path }}/rsync_{{ item | basename | regex_replace('[^a-zA-Z0-9]', '_') }}.log 2>&1
      loop: "{{ backup_src_paths }}"

    - name: Comprimir backup en tar.gz y eliminar carpeta sin comprimir
      ansible.builtin.archive:
        path: "{{ backup_dest_base }}"
        dest: "{{ compressed_file_path }}"
        format: gz
        remove: yes

    - name: Subir backup comprimido a Google Drive
      ansible.builtin.command: >
        rclone copy "{{ compressed_file_path }}" "gdrive:BACKUP/"

