---
- name: Backup remoto desde servidor Linux (cloud)
  hosts: localhost
  gather_facts: yes
  vars:
    target_host: srv_cloud  # â† clave: el nombre del host definido en tu inventory
    backup_src_paths:
      - "/root"
      - "/home/chichadepardos"
      - "/var/lib/docker"
      - "/etc/docker"
      - "/etc/containers"
    backup_dest_base: "/mnt/backups/{{ target_host }}/{{ ansible_date_time.date }}"
  tasks:
    - name: Obtener remote_user y remote_host desde hostvars
      set_fact:
        remote_user: "{{ hostvars[target_host]['remote_user'] }}"
        remote_host: "{{ hostvars[target_host]['remote_host'] }}"

    - name: Crear carpeta base para backups
      ansible.builtin.file:
        path: "{{ backup_dest_base }}"
        state: directory
        mode: '0755'
        recurse: yes

    - name: Ejecutar backup rsync por cada ruta
      ansible.builtin.command: >
        rsync -aAXv --delete
        -e "ssh -o StrictHostKeyChecking=no -tt"
        --rsync-path="sudo rsync"
        {{ remote_user }}@{{ remote_host }}:{{ item }}
        {{ backup_dest_base }}/{{ item | basename }}
      loop: "{{ backup_src_paths }}"
