- name: Actualizar todos los servidores
  hosts: todos
  become: true
  tasks:
    - name: Actualizar cache APT
      apt:
        update_cache: yes

    - name: Actualizar todos los paquetes
      apt:
        upgrade: dist
